package:
  name: "vaws"
  version: "3.5.3"
#  version: {{ environ['VERSION'] }}

source:
  path: ../

build:
  number: 1
  entry_points:
    - vaws = vaws.gui.main:run_gui
    - vaws_cmd = vaws.model.main:main

requirements:
  build:
    - python 3.7.1

  run:
    - matplotlib==3.0.3
    - h5py==2.8.0
    - pandas==1.2.4
    - python==3.7.1
    - scipy==1.4.1
    - shapely=1.6.4
    - markdown=3.0.1
test:
  imports:
    - vaws.model.main
    - vaws.gui.main

about:
  home: https://github.com/GeoscienceAustralia/vaws
  license: 'Copyright (c) 2015, Geoscience Australia'
  license_file: LICENSE
