package:
  name: "vaws"
  version: "3.5.0"
#  version: {{ environ['VERSION'] }}

source:
  path: ../

build:
  number: 1
  entry_points:
    - vaws = vaws.gui.main:run_gui
    - vaws_cmd = vaws.model.main:main

requirements:
  build:
    - python 3.6.7

  run:
    - matplotlib==3.0.3
    - h5py==2.8.0
    - numpy==1.16.4
    - pandas==0.23.4
    - python==3.6.7
    - scipy==1.2.1
    - shapely=1.6.4
test:
  imports:
    - vaws.model.main
    - vaws.gui.main

about:
  home: https://github.com/GeoscienceAustralia/vaws
  license: 'Copyright (c) 2015, Geoscience Australia'
  license_file: LICENSE
