# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName(_fromUtf8("main"))
        main.resize(1005, 673)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main.sizePolicy().hasHeightForWidth())
        main.setSizePolicy(sizePolicy)
        main.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/home2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(main)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scen_tab = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scen_tab.sizePolicy().hasHeightForWidth())
        self.scen_tab.setSizePolicy(sizePolicy)
        self.scen_tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scen_tab.setObjectName(_fromUtf8("scen_tab"))
        self.scenario_tab = QtGui.QWidget()
        self.scenario_tab.setObjectName(_fromUtf8("scenario_tab"))
        self.formLayout_3 = QtGui.QFormLayout(self.scenario_tab)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_12 = QtGui.QLabel(self.scenario_tab)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.numHouses = QtGui.QLineEdit(self.scenario_tab)
        self.numHouses.setObjectName(_fromUtf8("numHouses"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.numHouses)
        self.label_11 = QtGui.QLabel(self.scenario_tab)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label_16 = QtGui.QLabel(self.scenario_tab)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_16)
        self.terrainCategory = QtGui.QComboBox(self.scenario_tab)
        self.terrainCategory.setObjectName(_fromUtf8("terrainCategory"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.terrainCategory)
        self.label_17 = QtGui.QLabel(self.scenario_tab)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_17)
        self.regionalShielding = QtGui.QLineEdit(self.scenario_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regionalShielding.sizePolicy().hasHeightForWidth())
        self.regionalShielding.setSizePolicy(sizePolicy)
        self.regionalShielding.setObjectName(_fromUtf8("regionalShielding"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.regionalShielding)
        self.label_13 = QtGui.QLabel(self.scenario_tab)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_13)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.windMin = QtGui.QSlider(self.scenario_tab)
        self.windMin.setMinimum(0)
        self.windMin.setMaximum(200)
        self.windMin.setProperty("value", 0)
        self.windMin.setOrientation(QtCore.Qt.Horizontal)
        self.windMin.setTickPosition(QtGui.QSlider.NoTicks)
        self.windMin.setObjectName(_fromUtf8("windMin"))
        self.horizontalLayout_23.addWidget(self.windMin)
        self.windMinLabel = QtGui.QLabel(self.scenario_tab)
        self.windMinLabel.setObjectName(_fromUtf8("windMinLabel"))
        self.horizontalLayout_23.addWidget(self.windMinLabel)
        self.formLayout_3.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_23)
        self.label_14 = QtGui.QLabel(self.scenario_tab)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_14)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.windMax = QtGui.QSlider(self.scenario_tab)
        self.windMax.setMinimum(10)
        self.windMax.setMaximum(200)
        self.windMax.setOrientation(QtCore.Qt.Horizontal)
        self.windMax.setTickPosition(QtGui.QSlider.NoTicks)
        self.windMax.setObjectName(_fromUtf8("windMax"))
        self.horizontalLayout_25.addWidget(self.windMax)
        self.windMaxLabel = QtGui.QLabel(self.scenario_tab)
        self.windMaxLabel.setObjectName(_fromUtf8("windMaxLabel"))
        self.horizontalLayout_25.addWidget(self.windMaxLabel)
        self.formLayout_3.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout_25)
        self.label_15 = QtGui.QLabel(self.scenario_tab)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_15)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.windSteps = QtGui.QSlider(self.scenario_tab)
        self.windSteps.setMinimum(1)
        self.windSteps.setMaximum(500)
        self.windSteps.setOrientation(QtCore.Qt.Horizontal)
        self.windSteps.setTickPosition(QtGui.QSlider.NoTicks)
        self.windSteps.setObjectName(_fromUtf8("windSteps"))
        self.horizontalLayout_37.addWidget(self.windSteps)
        self.windStepsLabel = QtGui.QLabel(self.scenario_tab)
        self.windStepsLabel.setObjectName(_fromUtf8("windStepsLabel"))
        self.horizontalLayout_37.addWidget(self.windStepsLabel)
        self.formLayout_3.setLayout(6, QtGui.QFormLayout.FieldRole, self.horizontalLayout_37)
        self.label_20 = QtGui.QLabel(self.scenario_tab)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_20)
        self.windDirection = QtGui.QComboBox(self.scenario_tab)
        self.windDirection.setObjectName(_fromUtf8("windDirection"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.FieldRole, self.windDirection)
        self.houseName = QtGui.QLineEdit(self.scenario_tab)
        self.houseName.setObjectName(_fromUtf8("houseName"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.houseName)
        self.scen_tab.addTab(self.scenario_tab, _fromUtf8(""))
        self.debris_tab = QtGui.QWidget()
        self.debris_tab.setObjectName(_fromUtf8("debris_tab"))
        self.formLayout_2 = QtGui.QFormLayout(self.debris_tab)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_21 = QtGui.QLabel(self.debris_tab)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_21)
        self.debrisRegion = QtGui.QComboBox(self.debris_tab)
        self.debrisRegion.setObjectName(_fromUtf8("debrisRegion"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.debrisRegion)
        self.label_19 = QtGui.QLabel(self.debris_tab)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_19)
        self.buildingSpacing = QtGui.QComboBox(self.debris_tab)
        self.buildingSpacing.setObjectName(_fromUtf8("buildingSpacing"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.buildingSpacing)
        self.label_22 = QtGui.QLabel(self.debris_tab)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_22)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.debrisRadius = QtGui.QSlider(self.debris_tab)
        self.debrisRadius.setMinimum(10)
        self.debrisRadius.setMaximum(200)
        self.debrisRadius.setProperty("value", 100)
        self.debrisRadius.setOrientation(QtCore.Qt.Horizontal)
        self.debrisRadius.setTickPosition(QtGui.QSlider.NoTicks)
        self.debrisRadius.setTickInterval(0)
        self.debrisRadius.setObjectName(_fromUtf8("debrisRadius"))
        self.horizontalLayout_21.addWidget(self.debrisRadius)
        self.debrisRadiusLabel = QtGui.QLabel(self.debris_tab)
        self.debrisRadiusLabel.setObjectName(_fromUtf8("debrisRadiusLabel"))
        self.horizontalLayout_21.addWidget(self.debrisRadiusLabel)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_21)
        self.label_23 = QtGui.QLabel(self.debris_tab)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_23)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.debrisAngle = QtGui.QSlider(self.debris_tab)
        self.debrisAngle.setMinimum(20)
        self.debrisAngle.setMaximum(90)
        self.debrisAngle.setProperty("value", 90)
        self.debrisAngle.setOrientation(QtCore.Qt.Horizontal)
        self.debrisAngle.setTickPosition(QtGui.QSlider.NoTicks)
        self.debrisAngle.setTickInterval(0)
        self.debrisAngle.setObjectName(_fromUtf8("debrisAngle"))
        self.horizontalLayout_22.addWidget(self.debrisAngle)
        self.debrisAngleLabel = QtGui.QLabel(self.debris_tab)
        self.debrisAngleLabel.setObjectName(_fromUtf8("debrisAngleLabel"))
        self.horizontalLayout_22.addWidget(self.debrisAngleLabel)
        self.formLayout_2.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_22)
        self.label_24 = QtGui.QLabel(self.debris_tab)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_24)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.sourceItems = QtGui.QSlider(self.debris_tab)
        self.sourceItems.setMinimum(0)
        self.sourceItems.setMaximum(250)
        self.sourceItems.setProperty("value", 100)
        self.sourceItems.setOrientation(QtCore.Qt.Horizontal)
        self.sourceItems.setInvertedAppearance(False)
        self.sourceItems.setInvertedControls(False)
        self.sourceItems.setTickPosition(QtGui.QSlider.NoTicks)
        self.sourceItems.setTickInterval(0)
        self.sourceItems.setObjectName(_fromUtf8("sourceItems"))
        self.horizontalLayout_36.addWidget(self.sourceItems)
        self.sourceItemsLabel = QtGui.QLabel(self.debris_tab)
        self.sourceItemsLabel.setObjectName(_fromUtf8("sourceItemsLabel"))
        self.horizontalLayout_36.addWidget(self.sourceItemsLabel)
        self.formLayout_2.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_36)
        self.label_2 = QtGui.QLabel(self.debris_tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_2)
        self.flighttimeMean = QtGui.QLineEdit(self.debris_tab)
        self.flighttimeMean.setObjectName(_fromUtf8("flighttimeMean"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.flighttimeMean)
        self.label_3 = QtGui.QLabel(self.debris_tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_3)
        self.flighttimeStddev = QtGui.QLineEdit(self.debris_tab)
        self.flighttimeStddev.setObjectName(_fromUtf8("flighttimeStddev"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.flighttimeStddev)
        self.label_27 = QtGui.QLabel(self.debris_tab)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_27)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.staggeredDebrisSources = QtGui.QCheckBox(self.debris_tab)
        self.staggeredDebrisSources.setObjectName(_fromUtf8("staggeredDebrisSources"))
        self.horizontalLayout_18.addWidget(self.staggeredDebrisSources)
        self.debris = QtGui.QCheckBox(self.debris_tab)
        self.debris.setObjectName(_fromUtf8("debris"))
        self.horizontalLayout_18.addWidget(self.debris)
        self.testDebrisButton = QtGui.QPushButton(self.debris_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testDebrisButton.sizePolicy().hasHeightForWidth())
        self.testDebrisButton.setSizePolicy(sizePolicy)
        self.testDebrisButton.setObjectName(_fromUtf8("testDebrisButton"))
        self.horizontalLayout_18.addWidget(self.testDebrisButton)
        self.formLayout_2.setLayout(9, QtGui.QFormLayout.FieldRole, self.horizontalLayout_18)
        self.label_31 = QtGui.QLabel(self.debris_tab)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_31)
        self.debrisExtension = QtGui.QLineEdit(self.debris_tab)
        self.debrisExtension.setObjectName(_fromUtf8("debrisExtension"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.debrisExtension)
        self.scen_tab.addTab(self.debris_tab, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout = QtGui.QGridLayout(self.tab_7)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_8 = QtGui.QLabel(self.tab_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.lowProb = QtGui.QDoubleSpinBox(self.tab_7)
        self.lowProb.setMaximum(0.99)
        self.lowProb.setSingleStep(0.01)
        self.lowProb.setObjectName(_fromUtf8("lowProb"))
        self.gridLayout.addWidget(self.lowProb, 1, 1, 1, 1)
        self.lowMean = QtGui.QDoubleSpinBox(self.tab_7)
        self.lowMean.setMaximum(9.99)
        self.lowMean.setSingleStep(0.01)
        self.lowMean.setObjectName(_fromUtf8("lowMean"))
        self.gridLayout.addWidget(self.lowMean, 1, 2, 1, 1)
        self.lowCov = QtGui.QDoubleSpinBox(self.tab_7)
        self.lowCov.setMaximum(9.99)
        self.lowCov.setSingleStep(0.01)
        self.lowCov.setObjectName(_fromUtf8("lowCov"))
        self.gridLayout.addWidget(self.lowCov, 1, 3, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 2, 0, 1, 1)
        self.mediumProb = QtGui.QDoubleSpinBox(self.tab_7)
        self.mediumProb.setMaximum(0.99)
        self.mediumProb.setSingleStep(0.01)
        self.mediumProb.setObjectName(_fromUtf8("mediumProb"))
        self.gridLayout.addWidget(self.mediumProb, 2, 1, 1, 1)
        self.mediumMean = QtGui.QDoubleSpinBox(self.tab_7)
        self.mediumMean.setMaximum(9.99)
        self.mediumMean.setSingleStep(0.01)
        self.mediumMean.setObjectName(_fromUtf8("mediumMean"))
        self.gridLayout.addWidget(self.mediumMean, 2, 2, 1, 1)
        self.mediumCov = QtGui.QDoubleSpinBox(self.tab_7)
        self.mediumCov.setMaximum(9.99)
        self.mediumCov.setSingleStep(0.01)
        self.mediumCov.setObjectName(_fromUtf8("mediumCov"))
        self.gridLayout.addWidget(self.mediumCov, 2, 3, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 3, 0, 1, 1)
        self.highProb = QtGui.QDoubleSpinBox(self.tab_7)
        self.highProb.setMaximum(0.99)
        self.highProb.setSingleStep(0.01)
        self.highProb.setObjectName(_fromUtf8("highProb"))
        self.gridLayout.addWidget(self.highProb, 3, 1, 1, 1)
        self.highMean = QtGui.QDoubleSpinBox(self.tab_7)
        self.highMean.setMaximum(9.99)
        self.highMean.setSingleStep(0.01)
        self.highMean.setObjectName(_fromUtf8("highMean"))
        self.gridLayout.addWidget(self.highMean, 3, 2, 1, 1)
        self.highCov = QtGui.QDoubleSpinBox(self.tab_7)
        self.highCov.setMaximum(9.99)
        self.highCov.setSingleStep(0.01)
        self.highCov.setObjectName(_fromUtf8("highCov"))
        self.gridLayout.addWidget(self.highCov, 3, 3, 1, 1)
        self.testConstructionButton = QtGui.QPushButton(self.tab_7)
        self.testConstructionButton.setObjectName(_fromUtf8("testConstructionButton"))
        self.gridLayout.addWidget(self.testConstructionButton, 4, 3, 1, 1)
        self.constructionEnabled = QtGui.QCheckBox(self.tab_7)
        self.constructionEnabled.setObjectName(_fromUtf8("constructionEnabled"))
        self.gridLayout.addWidget(self.constructionEnabled, 4, 1, 1, 1)
        self.scen_tab.addTab(self.tab_7, _fromUtf8(""))
        self.display_tab = QtGui.QWidget()
        self.display_tab.setObjectName(_fromUtf8("display_tab"))
        self.formLayout = QtGui.QFormLayout(self.display_tab)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_6 = QtGui.QLabel(self.display_tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.redV = QtGui.QSlider(self.display_tab)
        self.redV.setMinimum(10)
        self.redV.setMaximum(200)
        self.redV.setProperty("value", 80)
        self.redV.setOrientation(QtCore.Qt.Horizontal)
        self.redV.setTickPosition(QtGui.QSlider.NoTicks)
        self.redV.setObjectName(_fromUtf8("redV"))
        self.horizontalLayout_27.addWidget(self.redV)
        self.redVLabel = QtGui.QLabel(self.display_tab)
        self.redVLabel.setObjectName(_fromUtf8("redVLabel"))
        self.horizontalLayout_27.addWidget(self.redVLabel)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_27)
        self.label_5 = QtGui.QLabel(self.display_tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.blueV = QtGui.QSlider(self.display_tab)
        self.blueV.setMinimum(10)
        self.blueV.setMaximum(200)
        self.blueV.setProperty("value", 40)
        self.blueV.setOrientation(QtCore.Qt.Horizontal)
        self.blueV.setTickPosition(QtGui.QSlider.NoTicks)
        self.blueV.setObjectName(_fromUtf8("blueV"))
        self.horizontalLayout_26.addWidget(self.blueV)
        self.blueVLabel = QtGui.QLabel(self.display_tab)
        self.blueVLabel.setObjectName(_fromUtf8("blueVLabel"))
        self.horizontalLayout_26.addWidget(self.blueVLabel)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_26)
        self.applyDisplayChangesButton = QtGui.QPushButton(self.display_tab)
        self.applyDisplayChangesButton.setObjectName(_fromUtf8("applyDisplayChangesButton"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.applyDisplayChangesButton)
        self.label = QtGui.QLabel(self.display_tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label)
        self.distribution = QtGui.QCheckBox(self.display_tab)
        self.distribution.setText(_fromUtf8(""))
        self.distribution.setObjectName(_fromUtf8("distribution"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.distribution)
        self.label_26 = QtGui.QLabel(self.display_tab)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_26)
        self.seedRandom = QtGui.QCheckBox(self.display_tab)
        self.seedRandom.setText(_fromUtf8(""))
        self.seedRandom.setObjectName(_fromUtf8("seedRandom"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.seedRandom)
        self.label_4 = QtGui.QLabel(self.display_tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_4)
        self.diffShielding = QtGui.QCheckBox(self.display_tab)
        self.diffShielding.setText(_fromUtf8(""))
        self.diffShielding.setObjectName(_fromUtf8("diffShielding"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.diffShielding)
        self.label_28 = QtGui.QLabel(self.display_tab)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_28)
        self.waterIngress = QtGui.QCheckBox(self.display_tab)
        self.waterIngress.setText(_fromUtf8(""))
        self.waterIngress.setObjectName(_fromUtf8("waterIngress"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.waterIngress)
        self.scen_tab.addTab(self.display_tab, _fromUtf8(""))
        self.tab_30 = QtGui.QWidget()
        self.tab_30.setObjectName(_fromUtf8("tab_30"))
        self.formLayout_4 = QtGui.QFormLayout(self.tab_30)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_32 = QtGui.QLabel(self.tab_30)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_32)
        self.slight = QtGui.QDoubleSpinBox(self.tab_30)
        self.slight.setSingleStep(0.01)
        self.slight.setObjectName(_fromUtf8("slight"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.slight)
        self.label_33 = QtGui.QLabel(self.tab_30)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_33)
        self.medium = QtGui.QDoubleSpinBox(self.tab_30)
        self.medium.setSingleStep(0.01)
        self.medium.setObjectName(_fromUtf8("medium"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.medium)
        self.label_34 = QtGui.QLabel(self.tab_30)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_34)
        self.severe = QtGui.QDoubleSpinBox(self.tab_30)
        self.severe.setSingleStep(0.01)
        self.severe.setObjectName(_fromUtf8("severe"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.severe)
        self.label_35 = QtGui.QLabel(self.tab_30)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_35)
        self.complete = QtGui.QDoubleSpinBox(self.tab_30)
        self.complete.setSingleStep(0.01)
        self.complete.setObjectName(_fromUtf8("complete"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.complete)
        self.scen_tab.addTab(self.tab_30, _fromUtf8(""))
        self.verticalLayout.addWidget(self.scen_tab)
        self.dataview_tab = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataview_tab.sizePolicy().hasHeightForWidth())
        self.dataview_tab.setSizePolicy(sizePolicy)
        self.dataview_tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dataview_tab.setTabPosition(QtGui.QTabWidget.North)
        self.dataview_tab.setObjectName(_fromUtf8("dataview_tab"))
        self.tab_15 = QtGui.QWidget()
        self.tab_15.setObjectName(_fromUtf8("tab_15"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.tab_15)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.houseinfo_tab = QtGui.QTabWidget(self.tab_15)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.houseinfo_tab.sizePolicy().hasHeightForWidth())
        self.houseinfo_tab.setSizePolicy(sizePolicy)
        self.houseinfo_tab.setTabPosition(QtGui.QTabWidget.South)
        self.houseinfo_tab.setObjectName(_fromUtf8("houseinfo_tab"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.connections = QtGui.QTableWidget(self.tab_4)
        self.connections.setProperty("showDropIndicator", False)
        self.connections.setDragDropOverwriteMode(False)
        self.connections.setAlternatingRowColors(False)
        self.connections.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.connections.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.connections.setColumnCount(6)
        self.connections.setObjectName(_fromUtf8("connections"))
        self.connections.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.connections.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.connections.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.connections.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.connections.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.connections.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.connections.setHorizontalHeaderItem(5, item)
        self.gridLayout_3.addWidget(self.connections, 0, 0, 1, 1)
        self.houseinfo_tab.addTab(self.tab_4, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.connectionsTypes = QtGui.QTableWidget(self.tab_3)
        self.connectionsTypes.setMinimumSize(QtCore.QSize(256, 0))
        self.connectionsTypes.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.connectionsTypes.setAlternatingRowColors(False)
        self.connectionsTypes.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.connectionsTypes.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.connectionsTypes.setColumnCount(7)
        self.connectionsTypes.setObjectName(_fromUtf8("connectionsTypes"))
        self.connectionsTypes.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.connectionsTypes.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.connectionsTypes.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.connectionsTypes.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.connectionsTypes.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.connectionsTypes.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.connectionsTypes.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.connectionsTypes.setHorizontalHeaderItem(6, item)
        self.horizontalLayout_2.addWidget(self.connectionsTypes)
        self.houseinfo_tab.addTab(self.tab_3, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab_8)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.connGroups = QtGui.QTableWidget(self.tab_8)
        self.connGroups.setObjectName(_fromUtf8("connGroups"))
        self.connGroups.setColumnCount(5)
        self.connGroups.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.connGroups.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.connGroups.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.connGroups.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.connGroups.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.connGroups.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_5.addWidget(self.connGroups)
        self.houseinfo_tab.addTab(self.tab_8, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_5)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.zones = QtGui.QTableWidget(self.tab_5)
        self.zones.setColumnCount(27)
        self.zones.setObjectName(_fromUtf8("zones"))
        self.zones.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(24, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(25, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(26, item)
        self.horizontalLayout_3.addWidget(self.zones)
        self.houseinfo_tab.addTab(self.tab_5, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.tab_11)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.damageScenarios = QtGui.QTableWidget(self.tab_11)
        self.damageScenarios.setMinimumSize(QtCore.QSize(256, 0))
        self.damageScenarios.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.damageScenarios.setAlternatingRowColors(False)
        self.damageScenarios.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.damageScenarios.setColumnCount(4)
        self.damageScenarios.setObjectName(_fromUtf8("damageScenarios"))
        self.damageScenarios.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.damageScenarios.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.damageScenarios.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.damageScenarios.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.damageScenarios.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_10.addWidget(self.damageScenarios)
        self.houseinfo_tab.addTab(self.tab_11, _fromUtf8(""))
        self.horizontalLayout_19.addWidget(self.houseinfo_tab)
        self.dataview_tab.addTab(self.tab_15, _fromUtf8(""))
        self.tab_16 = QtGui.QWidget()
        self.tab_16.setObjectName(_fromUtf8("tab_16"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.tab_16)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.tabWidget = QtGui.QTabWidget(self.tab_16)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_14 = QtGui.QWidget()
        self.tab_14.setObjectName(_fromUtf8("tab_14"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.tab_14)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.boundaryProfile = QtGui.QTableWidget(self.tab_14)
        self.boundaryProfile.setObjectName(_fromUtf8("boundaryProfile"))
        self.boundaryProfile.setColumnCount(11)
        self.boundaryProfile.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.boundaryProfile.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.boundaryProfile.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.boundaryProfile.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.boundaryProfile.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.boundaryProfile.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.boundaryProfile.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.boundaryProfile.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.boundaryProfile.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.boundaryProfile.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.boundaryProfile.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.boundaryProfile.setHorizontalHeaderItem(10, item)
        self.horizontalLayout_16.addWidget(self.boundaryProfile)
        self.tabWidget.addTab(self.tab_14, _fromUtf8(""))
        self.tab_17 = QtGui.QWidget()
        self.tab_17.setObjectName(_fromUtf8("tab_17"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.tab_17)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.debrisRegions = QtGui.QTableWidget(self.tab_17)
        self.debrisRegions.setObjectName(_fromUtf8("debrisRegions"))
        self.debrisRegions.setColumnCount(18)
        self.debrisRegions.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.debrisRegions.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.debrisRegions.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.debrisRegions.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.debrisRegions.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.debrisRegions.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.debrisRegions.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.debrisRegions.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.debrisRegions.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.debrisRegions.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.debrisRegions.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.debrisRegions.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.debrisRegions.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.debrisRegions.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.debrisRegions.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.debrisRegions.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.debrisRegions.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.debrisRegions.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.debrisRegions.setHorizontalHeaderItem(17, item)
        self.horizontalLayout_17.addWidget(self.debrisRegions)
        self.tabWidget.addTab(self.tab_17, _fromUtf8(""))
        self.tab_18 = QtGui.QWidget()
        self.tab_18.setObjectName(_fromUtf8("tab_18"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.tab_18)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.debrisTypes = QtGui.QTableWidget(self.tab_18)
        self.debrisTypes.setObjectName(_fromUtf8("debrisTypes"))
        self.debrisTypes.setColumnCount(2)
        self.debrisTypes.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.debrisTypes.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.debrisTypes.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_20.addWidget(self.debrisTypes)
        self.tabWidget.addTab(self.tab_18, _fromUtf8(""))
        self.horizontalLayout_15.addWidget(self.tabWidget)
        self.dataview_tab.addTab(self.tab_16, _fromUtf8(""))
        self.verticalLayout.addWidget(self.dataview_tab)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.resultsview_tab = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(99)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsview_tab.sizePolicy().hasHeightForWidth())
        self.resultsview_tab.setSizePolicy(sizePolicy)
        self.resultsview_tab.setObjectName(_fromUtf8("resultsview_tab"))
        self.tab_13 = QtGui.QWidget()
        self.tab_13.setObjectName(_fromUtf8("tab_13"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.tab_13)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.tabWidget_4 = QtGui.QTabWidget(self.tab_13)
        self.tabWidget_4.setTabPosition(QtGui.QTabWidget.East)
        self.tabWidget_4.setObjectName(_fromUtf8("tabWidget_4"))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.tab_10)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.zoneResults = QtGui.QTreeWidget(self.tab_10)
        self.zoneResults.setObjectName(_fromUtf8("zoneResults"))
        self.horizontalLayout_13.addWidget(self.zoneResults)
        self.tabWidget_4.addTab(self.tab_10, _fromUtf8(""))
        self.tab_22 = QtGui.QWidget()
        self.tab_22.setObjectName(_fromUtf8("tab_22"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.tab_22)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.connectionResults = QtGui.QTreeWidget(self.tab_22)
        self.connectionResults.setObjectName(_fromUtf8("connectionResults"))
        self.horizontalLayout_30.addWidget(self.connectionResults)
        self.tabWidget_4.addTab(self.tab_22, _fromUtf8(""))
        self.tab_23 = QtGui.QWidget()
        self.tab_23.setObjectName(_fromUtf8("tab_23"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout(self.tab_23)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.connection_type_plot = MatplotlibWidget(self.tab_23)
        self.connection_type_plot.setObjectName(_fromUtf8("connection_type_plot"))
        self.horizontalLayout_31.addWidget(self.connection_type_plot)
        self.tabWidget_4.addTab(self.tab_23, _fromUtf8(""))
        self.tab_28 = QtGui.QWidget()
        self.tab_28.setObjectName(_fromUtf8("tab_28"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.tab_28)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.connection_type_damages_plot = MatplotlibWidget(self.tab_28)
        self.connection_type_damages_plot.setObjectName(_fromUtf8("connection_type_damages_plot"))
        self.horizontalLayout_24.addWidget(self.connection_type_damages_plot)
        self.tabWidget_4.addTab(self.tab_28, _fromUtf8(""))
        self.horizontalLayout_29.addWidget(self.tabWidget_4)
        self.resultsview_tab.addTab(self.tab_13, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.damages_tab = QtGui.QTabWidget(self.tab)
        self.damages_tab.setTabPosition(QtGui.QTabWidget.East)
        self.damages_tab.setObjectName(_fromUtf8("damages_tab"))
        self.tab_19 = QtGui.QWidget()
        self.tab_19.setObjectName(_fromUtf8("tab_19"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.tab_19)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.mplsheeting = MatplotlibWidget(self.tab_19)
        self.mplsheeting.setObjectName(_fromUtf8("mplsheeting"))
        self.horizontalLayout_14.addWidget(self.mplsheeting)
        self.damages_tab.addTab(self.tab_19, _fromUtf8(""))
        self.tab_20 = QtGui.QWidget()
        self.tab_20.setObjectName(_fromUtf8("tab_20"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_20)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.mplbatten = MatplotlibWidget(self.tab_20)
        self.mplbatten.setObjectName(_fromUtf8("mplbatten"))
        self.horizontalLayout_7.addWidget(self.mplbatten)
        self.damages_tab.addTab(self.tab_20, _fromUtf8(""))
        self.tab_21 = QtGui.QWidget()
        self.tab_21.setObjectName(_fromUtf8("tab_21"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.tab_21)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.mplrafter = MatplotlibWidget(self.tab_21)
        self.mplrafter.setObjectName(_fromUtf8("mplrafter"))
        self.horizontalLayout_12.addWidget(self.mplrafter)
        self.damages_tab.addTab(self.tab_21, _fromUtf8(""))
        self.tab_25 = QtGui.QWidget()
        self.tab_25.setObjectName(_fromUtf8("tab_25"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout(self.tab_25)
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.mplwallracking = MatplotlibWidget(self.tab_25)
        self.mplwallracking.setObjectName(_fromUtf8("mplwallracking"))
        self.horizontalLayout_33.addWidget(self.mplwallracking)
        self.damages_tab.addTab(self.tab_25, _fromUtf8(""))
        self.tab_26 = QtGui.QWidget()
        self.tab_26.setObjectName(_fromUtf8("tab_26"))
        self.horizontalLayout_34 = QtGui.QHBoxLayout(self.tab_26)
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.mplwallcladding = MatplotlibWidget(self.tab_26)
        self.mplwallcladding.setObjectName(_fromUtf8("mplwallcladding"))
        self.horizontalLayout_34.addWidget(self.mplwallcladding)
        self.damages_tab.addTab(self.tab_26, _fromUtf8(""))
        self.tab_29 = QtGui.QWidget()
        self.tab_29.setObjectName(_fromUtf8("tab_29"))
        self.horizontalLayout_38 = QtGui.QHBoxLayout(self.tab_29)
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.mplwallcollapse = MatplotlibWidget(self.tab_29)
        self.mplwallcollapse.setObjectName(_fromUtf8("mplwallcollapse"))
        self.horizontalLayout_38.addWidget(self.mplwallcollapse)
        self.damages_tab.addTab(self.tab_29, _fromUtf8(""))
        self.tab_27 = QtGui.QWidget()
        self.tab_27.setObjectName(_fromUtf8("tab_27"))
        self.horizontalLayout_35 = QtGui.QHBoxLayout(self.tab_27)
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.mplpiers = MatplotlibWidget(self.tab_27)
        self.mplpiers.setObjectName(_fromUtf8("mplpiers"))
        self.horizontalLayout_35.addWidget(self.mplpiers)
        self.damages_tab.addTab(self.tab_27, _fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.damages_tab)
        self.resultsview_tab.addTab(self.tab, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.tab_9)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.tabWidget_3 = QtGui.QTabWidget(self.tab_9)
        self.tabWidget_3.setTabPosition(QtGui.QTabWidget.East)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_32 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.fitLognormalCurve = QtGui.QCheckBox(self.tab_2)
        self.fitLognormalCurve.setObjectName(_fromUtf8("fitLognormalCurve"))
        self.horizontalLayout_8.addWidget(self.fitLognormalCurve)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.label_29 = QtGui.QLabel(self.tab_2)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_8.addWidget(self.label_29)
        self.sumOfSquares = QtGui.QLineEdit(self.tab_2)
        self.sumOfSquares.setEnabled(True)
        self.sumOfSquares.setReadOnly(True)
        self.sumOfSquares.setObjectName(_fromUtf8("sumOfSquares"))
        self.horizontalLayout_8.addWidget(self.sumOfSquares)
        self.label_30 = QtGui.QLabel(self.tab_2)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_8.addWidget(self.label_30)
        self.coeff_1 = QtGui.QLineEdit(self.tab_2)
        self.coeff_1.setObjectName(_fromUtf8("coeff_1"))
        self.horizontalLayout_8.addWidget(self.coeff_1)
        self.coeff_2 = QtGui.QLineEdit(self.tab_2)
        self.coeff_2.setObjectName(_fromUtf8("coeff_2"))
        self.horizontalLayout_8.addWidget(self.coeff_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.mplvuln = MatplotlibWidget(self.tab_2)
        self.mplvuln.setObjectName(_fromUtf8("mplvuln"))
        self.verticalLayout_2.addWidget(self.mplvuln)
        self.horizontalLayout_32.addLayout(self.verticalLayout_2)
        self.tabWidget_3.addTab(self.tab_2, _fromUtf8(""))
        self.tab_12 = QtGui.QWidget()
        self.tab_12.setObjectName(_fromUtf8("tab_12"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.tab_12)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.mplfrag = MatplotlibWidget(self.tab_12)
        self.mplfrag.setObjectName(_fromUtf8("mplfrag"))
        self.horizontalLayout_9.addWidget(self.mplfrag)
        self.tabWidget_3.addTab(self.tab_12, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.wateringress_plot = MatplotlibWidget(self.tab_6)
        self.wateringress_plot.setObjectName(_fromUtf8("wateringress_plot"))
        self.horizontalLayout_4.addWidget(self.wateringress_plot)
        self.tabWidget_3.addTab(self.tab_6, _fromUtf8(""))
        self.tab_24 = QtGui.QWidget()
        self.tab_24.setObjectName(_fromUtf8("tab_24"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.tab_24)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.breaches_plot = MatplotlibWidget(self.tab_24)
        self.breaches_plot.setObjectName(_fromUtf8("breaches_plot"))
        self.horizontalLayout_11.addWidget(self.breaches_plot)
        self.tabWidget_3.addTab(self.tab_24, _fromUtf8(""))
        self.horizontalLayout_28.addWidget(self.tabWidget_3)
        self.resultsview_tab.addTab(self.tab_9, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.resultsview_tab)
        main.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1005, 15))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSimulator = QtGui.QMenu(self.menubar)
        self.menuSimulator.setObjectName(_fromUtf8("menuSimulator"))
        self.menuModel = QtGui.QMenu(self.menubar)
        self.menuModel.setObjectName(_fromUtf8("menuModel"))
        main.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(main)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        main.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(main)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        main.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen_Scenario = QtGui.QAction(main)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/fileopen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Scenario.setIcon(icon1)
        self.actionOpen_Scenario.setObjectName(_fromUtf8("actionOpen_Scenario"))
        self.actionRun = QtGui.QAction(main)
        self.actionRun.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon2)
        self.actionRun.setObjectName(_fromUtf8("actionRun"))
        self.actionStop = QtGui.QAction(main)
        self.actionStop.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/filequit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon3)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionSave_Scenario = QtGui.QAction(main)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/filesave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_Scenario.setIcon(icon4)
        self.actionSave_Scenario.setObjectName(_fromUtf8("actionSave_Scenario"))
        self.actionNew_Scenario = QtGui.QAction(main)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/filenew.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_Scenario.setIcon(icon5)
        self.actionNew_Scenario.setObjectName(_fromUtf8("actionNew_Scenario"))
        self.actionSave_Scenario_As = QtGui.QAction(main)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/filesaveas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_Scenario_As.setIcon(icon6)
        self.actionSave_Scenario_As.setObjectName(_fromUtf8("actionSave_Scenario_As"))
        self.actionHouse_Info = QtGui.QAction(main)
        self.actionHouse_Info.setIcon(icon)
        self.actionHouse_Info.setObjectName(_fromUtf8("actionHouse_Info"))
        self.actionTest_Debris_Settings = QtGui.QAction(main)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/fan.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTest_Debris_Settings.setIcon(icon7)
        self.actionTest_Debris_Settings.setObjectName(_fromUtf8("actionTest_Debris_Settings"))
        self.actionInfo = QtGui.QAction(main)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/editzoom.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInfo.setIcon(icon8)
        self.actionInfo.setObjectName(_fromUtf8("actionInfo"))
        self.menuFile.addAction(self.actionNew_Scenario)
        self.menuFile.addAction(self.actionOpen_Scenario)
        self.menuFile.addAction(self.actionSave_Scenario)
        self.menuFile.addAction(self.actionSave_Scenario_As)
        self.menuSimulator.addAction(self.actionRun)
        self.menuSimulator.addAction(self.actionStop)
        self.menuModel.addAction(self.actionHouse_Info)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSimulator.menuAction())
        self.menubar.addAction(self.menuModel.menuAction())
        self.toolBar.addAction(self.actionOpen_Scenario)
        self.toolBar.addAction(self.actionNew_Scenario)
        self.toolBar.addAction(self.actionSave_Scenario)
        self.toolBar.addAction(self.actionSave_Scenario_As)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHouse_Info)
        self.toolBar.addAction(self.actionInfo)

        self.retranslateUi(main)
        self.scen_tab.setCurrentIndex(0)
        self.dataview_tab.setCurrentIndex(0)
        self.houseinfo_tab.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.resultsview_tab.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.damages_tab.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        main.setWindowTitle(_translate("main", "Component Wind Simulator", None))
        self.label_12.setText(_translate("main", "Number of Houses:", None))
        self.label_11.setText(_translate("main", "House Name:", None))
        self.label_16.setText(_translate("main", "Terrain Category:", None))
        self.label_17.setText(_translate("main", "Regional Shielding:", None))
        self.label_13.setText(_translate("main", "Wind Speed Min:", None))
        self.windMinLabel.setText(_translate("main", "100", None))
        self.label_14.setText(_translate("main", "Wind Speed Max:", None))
        self.windMaxLabel.setText(_translate("main", "100", None))
        self.label_15.setText(_translate("main", "Wind Speed Steps:", None))
        self.windStepsLabel.setText(_translate("main", "100", None))
        self.label_20.setText(_translate("main", "Wind Direction:", None))
        self.scen_tab.setTabText(self.scen_tab.indexOf(self.scenario_tab), _translate("main", "Scenario", None))
        self.label_21.setText(_translate("main", "Region:", None))
        self.label_19.setText(_translate("main", "Building Spacing:", None))
        self.label_22.setText(_translate("main", "Radius:", None))
        self.debrisRadiusLabel.setText(_translate("main", "100", None))
        self.label_23.setText(_translate("main", "Angle:", None))
        self.debrisAngleLabel.setText(_translate("main", "0", None))
        self.label_24.setText(_translate("main", "Source Items:", None))
        self.sourceItemsLabel.setText(_translate("main", "0", None))
        self.label_2.setText(_translate("main", "Flighttime Mean:", None))
        self.label_3.setText(_translate("main", "Flighttime StdDev:", None))
        self.label_27.setText(_translate("main", "Options:", None))
        self.staggeredDebrisSources.setText(_translate("main", "Staggered Sources", None))
        self.debris.setText(_translate("main", "Enabled", None))
        self.testDebrisButton.setText(_translate("main", "Test...", None))
        self.label_31.setText(_translate("main", "Extension (m):", None))
        self.scen_tab.setTabText(self.scen_tab.indexOf(self.debris_tab), _translate("main", "Debris", None))
        self.label_8.setText(_translate("main", "Probability", None))
        self.label_9.setText(_translate("main", "Mean Factor", None))
        self.label_10.setText(_translate("main", "Cov Factor", None))
        self.label_7.setText(_translate("main", "Low:", None))
        self.label_18.setText(_translate("main", "Medium:", None))
        self.label_25.setText(_translate("main", "High:", None))
        self.testConstructionButton.setText(_translate("main", "Test...", None))
        self.constructionEnabled.setText(_translate("main", "Enabled", None))
        self.scen_tab.setTabText(self.scen_tab.indexOf(self.tab_7), _translate("main", "Construction", None))
        self.label_6.setText(_translate("main", "Red V:", None))
        self.redVLabel.setText(_translate("main", "100", None))
        self.label_5.setText(_translate("main", "Blue V:", None))
        self.blueVLabel.setText(_translate("main", "100", None))
        self.applyDisplayChangesButton.setText(_translate("main", "Update Display", None))
        self.label.setText(_translate("main", "Distribute Damage:", None))
        self.label_26.setText(_translate("main", "Seed Random Numbers:", None))
        self.label_4.setText(_translate("main", "Differential Shielding:", None))
        self.label_28.setText(_translate("main", "Water Ingress:", None))
        self.scen_tab.setTabText(self.scen_tab.indexOf(self.display_tab), _translate("main", "Options", None))
        self.label_32.setText(_translate("main", "Slight:", None))
        self.label_33.setText(_translate("main", "Medium:", None))
        self.label_34.setText(_translate("main", "Severe:", None))
        self.label_35.setText(_translate("main", "Complete:", None))
        self.scen_tab.setTabText(self.scen_tab.indexOf(self.tab_30), _translate("main", "Fragility", None))
        item = self.connections.horizontalHeaderItem(0)
        item.setText(_translate("main", "Name", None))
        item = self.connections.horizontalHeaderItem(1)
        item.setText(_translate("main", "Type", None))
        item = self.connections.horizontalHeaderItem(2)
        item.setText(_translate("main", "Zone", None))
        item = self.connections.horizontalHeaderItem(3)
        item.setText(_translate("main", "Edge", None))
        item = self.connections.horizontalHeaderItem(4)
        item.setText(_translate("main", "Broken_Avg", None))
        item = self.connections.horizontalHeaderItem(5)
        item.setText(_translate("main", "Broken_Count", None))
        self.houseinfo_tab.setTabText(self.houseinfo_tab.indexOf(self.tab_4), _translate("main", "Connections", None))
        item = self.connectionsTypes.horizontalHeaderItem(0)
        item.setText(_translate("main", "Type", None))
        item = self.connectionsTypes.horizontalHeaderItem(1)
        item.setText(_translate("main", "S Mean", None))
        item = self.connectionsTypes.horizontalHeaderItem(2)
        item.setText(_translate("main", "S Stddev", None))
        item = self.connectionsTypes.horizontalHeaderItem(3)
        item.setText(_translate("main", "D Mean", None))
        item = self.connectionsTypes.horizontalHeaderItem(4)
        item.setText(_translate("main", "D Stddev", None))
        item = self.connectionsTypes.horizontalHeaderItem(5)
        item.setText(_translate("main", "Group", None))
        item = self.connectionsTypes.horizontalHeaderItem(6)
        item.setText(_translate("main", "Costing Area", None))
        self.houseinfo_tab.setTabText(self.houseinfo_tab.indexOf(self.tab_3), _translate("main", "Types", None))
        item = self.connGroups.horizontalHeaderItem(0)
        item.setText(_translate("main", "Name", None))
        item = self.connGroups.horizontalHeaderItem(1)
        item.setText(_translate("main", "Order", None))
        item = self.connGroups.horizontalHeaderItem(2)
        item.setText(_translate("main", "Distribute By", None))
        item = self.connGroups.horizontalHeaderItem(3)
        item.setText(_translate("main", "Dmg Scen", None))
        item = self.connGroups.horizontalHeaderItem(4)
        item.setText(_translate("main", "Enabled", None))
        self.houseinfo_tab.setTabText(self.houseinfo_tab.indexOf(self.tab_8), _translate("main", "Groups", None))
        item = self.zones.horizontalHeaderItem(0)
        item.setText(_translate("main", "Name", None))
        item = self.zones.horizontalHeaderItem(1)
        item.setText(_translate("main", "Area", None))
        item = self.zones.horizontalHeaderItem(2)
        item.setText(_translate("main", "CpiAlpha", None))
        item = self.zones.horizontalHeaderItem(3)
        item.setText(_translate("main", "S", None))
        item = self.zones.horizontalHeaderItem(4)
        item.setText(_translate("main", "SW", None))
        item = self.zones.horizontalHeaderItem(5)
        item.setText(_translate("main", "W", None))
        item = self.zones.horizontalHeaderItem(6)
        item.setText(_translate("main", "NW", None))
        item = self.zones.horizontalHeaderItem(7)
        item.setText(_translate("main", "N", None))
        item = self.zones.horizontalHeaderItem(8)
        item.setText(_translate("main", "NE", None))
        item = self.zones.horizontalHeaderItem(9)
        item.setText(_translate("main", "E", None))
        item = self.zones.horizontalHeaderItem(10)
        item.setText(_translate("main", "SE", None))
        item = self.zones.horizontalHeaderItem(11)
        item.setText(_translate("main", "sS", None))
        item = self.zones.horizontalHeaderItem(12)
        item.setText(_translate("main", "sSW", None))
        item = self.zones.horizontalHeaderItem(13)
        item.setText(_translate("main", "sW", None))
        item = self.zones.horizontalHeaderItem(14)
        item.setText(_translate("main", "sNW", None))
        item = self.zones.horizontalHeaderItem(15)
        item.setText(_translate("main", "sN", None))
        item = self.zones.horizontalHeaderItem(16)
        item.setText(_translate("main", "sNE", None))
        item = self.zones.horizontalHeaderItem(17)
        item.setText(_translate("main", "sE", None))
        item = self.zones.horizontalHeaderItem(18)
        item.setText(_translate("main", "sSE", None))
        item = self.zones.horizontalHeaderItem(19)
        item.setText(_translate("main", "eS", None))
        item = self.zones.horizontalHeaderItem(20)
        item.setText(_translate("main", "eSW", None))
        item = self.zones.horizontalHeaderItem(21)
        item.setText(_translate("main", "eW", None))
        item = self.zones.horizontalHeaderItem(22)
        item.setText(_translate("main", "eNW", None))
        item = self.zones.horizontalHeaderItem(23)
        item.setText(_translate("main", "eN", None))
        item = self.zones.horizontalHeaderItem(24)
        item.setText(_translate("main", "eNE", None))
        item = self.zones.horizontalHeaderItem(25)
        item.setText(_translate("main", "eE", None))
        item = self.zones.horizontalHeaderItem(26)
        item.setText(_translate("main", "eSE", None))
        self.houseinfo_tab.setTabText(self.houseinfo_tab.indexOf(self.tab_5), _translate("main", "Zones", None))
        item = self.damageScenarios.horizontalHeaderItem(0)
        item.setText(_translate("main", "Name", None))
        item = self.damageScenarios.horizontalHeaderItem(1)
        item.setText(_translate("main", "Area", None))
        item = self.damageScenarios.horizontalHeaderItem(2)
        item.setText(_translate("main", "Env Repair Rate", None))
        item = self.damageScenarios.horizontalHeaderItem(3)
        item.setText(_translate("main", "Int Repair Rate", None))
        self.houseinfo_tab.setTabText(self.houseinfo_tab.indexOf(self.tab_11), _translate("main", "Damage", None))
        self.dataview_tab.setTabText(self.dataview_tab.indexOf(self.tab_15), _translate("main", "House", None))
        item = self.boundaryProfile.horizontalHeaderItem(0)
        item.setText(_translate("main", "Height", None))
        item = self.boundaryProfile.horizontalHeaderItem(1)
        item.setText(_translate("main", "P1", None))
        item = self.boundaryProfile.horizontalHeaderItem(2)
        item.setText(_translate("main", "P2", None))
        item = self.boundaryProfile.horizontalHeaderItem(3)
        item.setText(_translate("main", "P3", None))
        item = self.boundaryProfile.horizontalHeaderItem(4)
        item.setText(_translate("main", "P4", None))
        item = self.boundaryProfile.horizontalHeaderItem(5)
        item.setText(_translate("main", "P5", None))
        item = self.boundaryProfile.horizontalHeaderItem(6)
        item.setText(_translate("main", "P6", None))
        item = self.boundaryProfile.horizontalHeaderItem(7)
        item.setText(_translate("main", "P7", None))
        item = self.boundaryProfile.horizontalHeaderItem(8)
        item.setText(_translate("main", "P8", None))
        item = self.boundaryProfile.horizontalHeaderItem(9)
        item.setText(_translate("main", "P9", None))
        item = self.boundaryProfile.horizontalHeaderItem(10)
        item.setText(_translate("main", "P10", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_14), _translate("main", "Boundary Profile", None))
        item = self.debrisRegions.horizontalHeaderItem(0)
        item.setText(_translate("main", "Name", None))
        item = self.debrisRegions.horizontalHeaderItem(1)
        item.setText(_translate("main", "vuln_alpha", None))
        item = self.debrisRegions.horizontalHeaderItem(2)
        item.setText(_translate("main", "vuln_beta", None))
        item = self.debrisRegions.horizontalHeaderItem(3)
        item.setText(_translate("main", "cr", None))
        item = self.debrisRegions.horizontalHeaderItem(4)
        item.setText(_translate("main", "cmm", None))
        item = self.debrisRegions.horizontalHeaderItem(5)
        item.setText(_translate("main", "cmc", None))
        item = self.debrisRegions.horizontalHeaderItem(6)
        item.setText(_translate("main", "cfm", None))
        item = self.debrisRegions.horizontalHeaderItem(7)
        item.setText(_translate("main", "cfc", None))
        item = self.debrisRegions.horizontalHeaderItem(8)
        item.setText(_translate("main", "rr", None))
        item = self.debrisRegions.horizontalHeaderItem(9)
        item.setText(_translate("main", "rmm", None))
        item = self.debrisRegions.horizontalHeaderItem(10)
        item.setText(_translate("main", "rmc", None))
        item = self.debrisRegions.horizontalHeaderItem(11)
        item.setText(_translate("main", "rfm", None))
        item = self.debrisRegions.horizontalHeaderItem(12)
        item.setText(_translate("main", "rfc", None))
        item = self.debrisRegions.horizontalHeaderItem(13)
        item.setText(_translate("main", "pr", None))
        item = self.debrisRegions.horizontalHeaderItem(14)
        item.setText(_translate("main", "pmm", None))
        item = self.debrisRegions.horizontalHeaderItem(15)
        item.setText(_translate("main", "pmc", None))
        item = self.debrisRegions.horizontalHeaderItem(16)
        item.setText(_translate("main", "pfm", None))
        item = self.debrisRegions.horizontalHeaderItem(17)
        item.setText(_translate("main", "pfc", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_17), _translate("main", "Debris Regions", None))
        item = self.debrisTypes.horizontalHeaderItem(0)
        item.setText(_translate("main", "New Column", None))
        item = self.debrisTypes.horizontalHeaderItem(1)
        item.setText(_translate("main", "CDAv", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_18), _translate("main", "Debris Types", None))
        self.dataview_tab.setTabText(self.dataview_tab.indexOf(self.tab_16), _translate("main", "Global", None))
        self.zoneResults.headerItem().setText(0, _translate("main", "House", None))
        self.zoneResults.headerItem().setText(1, _translate("main", "Zone", None))
        self.zoneResults.headerItem().setText(2, _translate("main", "cpe", None))
        self.zoneResults.headerItem().setText(3, _translate("main", "cpestr", None))
        self.zoneResults.headerItem().setText(4, _translate("main", "cpeeav", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_10), _translate("main", "Zones", None))
        self.connectionResults.headerItem().setText(0, _translate("main", "Name", None))
        self.connectionResults.headerItem().setText(1, _translate("main", "BrokeAt", None))
        self.connectionResults.headerItem().setText(2, _translate("main", "Strength", None))
        self.connectionResults.headerItem().setText(3, _translate("main", "DeadLoad", None))
        self.connectionResults.headerItem().setText(4, _translate("main", "Damaged Load", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_22), _translate("main", "Connections", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_23), _translate("main", "Type Strengths", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_28), _translate("main", "Type Damage", None))
        self.resultsview_tab.setTabText(self.resultsview_tab.indexOf(self.tab_13), _translate("main", "Results", None))
        self.damages_tab.setTabText(self.damages_tab.indexOf(self.tab_19), _translate("main", "Sheeting", None))
        self.damages_tab.setTabText(self.damages_tab.indexOf(self.tab_20), _translate("main", "Batten", None))
        self.damages_tab.setTabText(self.damages_tab.indexOf(self.tab_21), _translate("main", "Rafter", None))
        self.damages_tab.setTabText(self.damages_tab.indexOf(self.tab_25), _translate("main", "WallRacking", None))
        self.damages_tab.setTabText(self.damages_tab.indexOf(self.tab_26), _translate("main", "WallCladding", None))
        self.damages_tab.setTabText(self.damages_tab.indexOf(self.tab_29), _translate("main", "WallCollapse", None))
        self.damages_tab.setTabText(self.damages_tab.indexOf(self.tab_27), _translate("main", "PiersGroup", None))
        self.resultsview_tab.setTabText(self.resultsview_tab.indexOf(self.tab), _translate("main", "Damages", None))
        self.fitLognormalCurve.setText(_translate("main", "Fit Lognormal Curve", None))
        self.label_29.setText(_translate("main", "Sum of Squares :", None))
        self.label_30.setText(_translate("main", "Coeffs:", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_2), _translate("main", "Vulnerability", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_12), _translate("main", "Fragility", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("main", "Water Ingress", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_24), _translate("main", "Debris", None))
        self.resultsview_tab.setTabText(self.resultsview_tab.indexOf(self.tab_9), _translate("main", "Curves", None))
        self.menuFile.setTitle(_translate("main", "File", None))
        self.menuSimulator.setTitle(_translate("main", "Simulator", None))
        self.menuModel.setTitle(_translate("main", "Model", None))
        self.toolBar.setWindowTitle(_translate("main", "toolBar", None))
        self.actionOpen_Scenario.setText(_translate("main", "Open Scenario...", None))
        self.actionRun.setText(_translate("main", "Run", None))
        self.actionStop.setText(_translate("main", "Stop", None))
        self.actionSave_Scenario.setText(_translate("main", "Save", None))
        self.actionNew_Scenario.setText(_translate("main", "New...", None))
        self.actionSave_Scenario_As.setText(_translate("main", "Save As...", None))
        self.actionHouse_Info.setText(_translate("main", "House Info...", None))
        self.actionTest_Debris_Settings.setText(_translate("main", "Test Debris Settings...", None))
        self.actionInfo.setText(_translate("main", "Info", None))
        self.actionInfo.setToolTip(_translate("main", "Get Info...", None))

from matplotlibwidget import MatplotlibWidget
import windsim_rc
