# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/zone.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(853, 628)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/editresize.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.area = QtGui.QLineEdit(Dialog)
        self.area.setObjectName(_fromUtf8("area"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.area)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.cpi_alpha = QtGui.QLineEdit(Dialog)
        self.cpi_alpha.setObjectName(_fromUtf8("cpi_alpha"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.cpi_alpha)
        self.label_9 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_9)
        self.house_cpe_k = QtGui.QLineEdit(Dialog)
        self.house_cpe_k.setEnabled(False)
        self.house_cpe_k.setReadOnly(True)
        self.house_cpe_k.setObjectName(_fromUtf8("house_cpe_k"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.house_cpe_k)
        self.label_10 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_10)
        self.house_cpe_v = QtGui.QLineEdit(Dialog)
        self.house_cpe_v.setEnabled(False)
        self.house_cpe_v.setReadOnly(True)
        self.house_cpe_v.setObjectName(_fromUtf8("house_cpe_v"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.house_cpe_v)
        self.label_15 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_15)
        self.house_cpe_struct_v = QtGui.QLineEdit(Dialog)
        self.house_cpe_struct_v.setEnabled(False)
        self.house_cpe_struct_v.setReadOnly(True)
        self.house_cpe_struct_v.setObjectName(_fromUtf8("house_cpe_struct_v"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.house_cpe_struct_v)
        self.zone_name = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.zone_name.setFont(font)
        self.zone_name.setObjectName(_fromUtf8("zone_name"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.zone_name)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.sometab = QtGui.QTabWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.sometab.sizePolicy().hasHeightForWidth())
        self.sometab.setSizePolicy(sizePolicy)
        self.sometab.setObjectName(_fromUtf8("sometab"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.table = QtGui.QTableWidget(self.tab)
        self.table.setObjectName(_fromUtf8("table"))
        self.table.setColumnCount(4)
        self.table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        self.gridLayout_2.addWidget(self.table, 0, 0, 2, 1)
        self.pdf_plot_button = QtGui.QPushButton(self.tab)
        self.pdf_plot_button.setObjectName(_fromUtf8("pdf_plot_button"))
        self.gridLayout_2.addWidget(self.pdf_plot_button, 0, 1, 1, 1)
        self.pdf_plot = MatplotlibWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(99)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdf_plot.sizePolicy().hasHeightForWidth())
        self.pdf_plot.setSizePolicy(sizePolicy)
        self.pdf_plot.setObjectName(_fromUtf8("pdf_plot"))
        self.gridLayout_2.addWidget(self.pdf_plot, 1, 1, 1, 1)
        self.sometab.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.zones = QtGui.QTableWidget(self.tab_3)
        self.zones.setShowGrid(False)
        self.zones.setObjectName(_fromUtf8("zones"))
        self.zones.setColumnCount(4)
        self.zones.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.zones.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_3.addWidget(self.zones)
        self.sometab.addTab(self.tab_3, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout = QtGui.QGridLayout(self.tab_5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_8 = QtGui.QLabel(self.tab_5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.group_filter = QtGui.QComboBox(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(99)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_filter.sizePolicy().hasHeightForWidth())
        self.group_filter.setSizePolicy(sizePolicy)
        self.group_filter.setObjectName(_fromUtf8("group_filter"))
        self.group_filter.addItem(_fromUtf8(""))
        self.group_filter.addItem(_fromUtf8(""))
        self.group_filter.addItem(_fromUtf8(""))
        self.group_filter.addItem(_fromUtf8(""))
        self.group_filter.addItem(_fromUtf8(""))
        self.group_filter.addItem(_fromUtf8(""))
        self.group_filter.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.group_filter, 0, 1, 1, 1)
        self.line = QtGui.QFrame(self.tab_5)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 0, 1, 2)
        self.connections = QtGui.QTreeWidget(self.tab_5)
        self.connections.setObjectName(_fromUtf8("connections"))
        self.gridLayout.addWidget(self.connections, 2, 0, 1, 2)
        self.sometab.addTab(self.tab_5, _fromUtf8(""))
        self.verticalLayout.addWidget(self.sometab)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.NoButton)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.sometab.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.area, self.cpi_alpha)
        Dialog.setTabOrder(self.cpi_alpha, self.zones)
        Dialog.setTabOrder(self.zones, self.buttonBox)
        Dialog.setTabOrder(self.buttonBox, self.connections)
        Dialog.setTabOrder(self.connections, self.group_filter)
        Dialog.setTabOrder(self.group_filter, self.sometab)
        Dialog.setTabOrder(self.sometab, self.house_cpe_struct_v)
        Dialog.setTabOrder(self.house_cpe_struct_v, self.house_cpe_v)
        Dialog.setTabOrder(self.house_cpe_v, self.house_cpe_k)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Zone Browser", None))
        self.label.setText(_translate("Dialog", "Zone:", None))
        self.label_2.setText(_translate("Dialog", "Area:", None))
        self.label_7.setText(_translate("Dialog", "Cpi Alpha:", None))
        self.label_9.setText(_translate("Dialog", "House Cpe_k:", None))
        self.label_10.setText(_translate("Dialog", "House Cpe_V:", None))
        self.label_15.setText(_translate("Dialog", "House Cpe_struct_V:", None))
        self.zone_name.setText(_translate("Dialog", "TextLabel", None))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Direction", None))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Coeff", None))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Structural", None))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Eaves", None))
        self.pdf_plot_button.setText(_translate("Dialog", "Plot", None))
        self.sometab.setTabText(self.sometab.indexOf(self.tab), _translate("Dialog", "Pressure Coefficients", None))
        item = self.zones.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Name", None))
        item = self.zones.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Cpe", None))
        item = self.zones.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Cpe_struct", None))
        item = self.zones.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Cpe_eaves", None))
        self.sometab.setTabText(self.sometab.indexOf(self.tab_3), _translate("Dialog", "Simulated Zones", None))
        self.label_8.setText(_translate("Dialog", "Filter By Group:", None))
        self.group_filter.setItemText(0, _translate("Dialog", "All", None))
        self.group_filter.setItemText(1, _translate("Dialog", "Sheeting", None))
        self.group_filter.setItemText(2, _translate("Dialog", "Batten", None))
        self.group_filter.setItemText(3, _translate("Dialog", "Rafter", None))
        self.group_filter.setItemText(4, _translate("Dialog", "WallRacking", None))
        self.group_filter.setItemText(5, _translate("Dialog", "WallCladding", None))
        self.group_filter.setItemText(6, _translate("Dialog", "PiersGroup", None))
        self.connections.headerItem().setText(0, _translate("Dialog", "Name", None))
        self.connections.headerItem().setText(1, _translate("Dialog", "Broke At", None))
        self.connections.headerItem().setText(2, _translate("Dialog", "Strength", None))
        self.connections.headerItem().setText(3, _translate("Dialog", "Dead Load", None))
        self.connections.headerItem().setText(4, _translate("Dialog", "Damaged Load", None))
        self.sometab.setTabText(self.sometab.indexOf(self.tab_5), _translate("Dialog", "Simulated Connections", None))

from matplotlibwidget import MatplotlibWidget
import windsim_rc
